# Generated by Django 5.2.7 on 2025-11-04 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolEventTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('user_id', models.CharField(blank=True, max_length=50, null=True)),
                ('user_name', models.CharField(blank=True, max_length=100, null=True)),
                ('event', models.CharField(choices=[('tray_open', 'Tray Open'), ('tray_close', 'Tray Close'), ('tool_Issued', 'Tool Issued'), ('tool_Returned', 'Tool Returned'), ('auto_logout', 'Auto Logout'), ('system_offline', 'System Offline')], max_length=50)),
                ('tray_id', models.IntegerField(blank=True, null=True)),
                ('cart_id', models.IntegerField(blank=True, null=True)),
                ('tool_id', models.IntegerField(blank=True, null=True)),
                ('tool_name', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
