# Generated by Django 5.2.7 on 2025-10-29 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_remove_toolcreation_calibration'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=200)),
                ('invoice_number', models.CharField(max_length=100)),
                ('purchase_date', models.DateField()),
                ('calibration', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detection.toolcreation')),
            ],
        ),
    ]
