# Generated by Django 5.2.7 on 2025-11-04 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_tooleventtracking'),
    ]

