# Generated by Django 5.2.7 on 2025-11-04 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0003_delete_toolevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tooleventtracking',
            name='tool_id',
            field=models.CharField(blank=True, null=True),
        ),
    ]
