# Generated by Django 5.2.7 on 2025-10-29 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0003_toolpurchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolpurchase',
            name='purchase_cost',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
