# Generated by Django 5.2.7 on 2025-11-04 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0004_delete_toolevent_alter_tooleventtracking_tool_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tooleventtracking',
            name='event',
            field=models.CharField(choices=[('tray_open', 'Tray Open'), ('tray_close', 'Tray Close'), ('tool_Issued', 'Tool Issued'), ('tool_Returned', 'Tool Returned'), ('tool_Damaged', 'Tool Damaged'), ('auto_logout', 'Auto Logout'), ('system_offline', 'System Offline')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tooleventtracking',
            name='tool_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
