# Generated by Django 5.2.7 on 2025-10-29 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0004_toolpurchase_purchase_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inventory_id', models.AutoField(primary_key=True, serialize=False)),
                ('tool_name', models.CharField(max_length=200)),
                ('part_number', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(default='Warehouse', max_length=100)),
                ('batch_number', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_number', models.CharField(max_length=100)),
                ('total_quantity', models.PositiveIntegerField(default=0)),
                ('assigned_quantity', models.PositiveIntegerField(default=0)),
                ('available_quantity', models.PositiveIntegerField(default=0)),
                ('in_use', models.PositiveIntegerField(default=0)),
                ('damaged', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detection.toolcreation')),
            ],
        ),
    ]
