# Generated by Django 5.2.7 on 2025-11-04 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0005_delete_toolevent_alter_tooleventtracking_event_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tooleventtracking',
            old_name='cart_id',
            new_name='unit_id',
        ),
    ]
