# Generated by Django 5.2.7 on 2025-10-29 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0005_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolpurchase',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='toolpurchase',
            name='unit_cost',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
