# Generated by Django 5.2.7 on 2025-11-06 07:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0006_delete_toolevent_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ToolsTracking',
        ),
        migrations.AddField(
            model_name='tooleventtracking',
            name='client_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tooleventtracking',
            name='device_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tooleventtracking',
            name='raw_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tooleventtracking',
            name='service_station',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tooleventtracking',
            name='unit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tooleventtracking',
            name='event',
            field=models.CharField(choices=[('tray_open', 'Tray Open'), ('tray_close', 'Tray Close'), ('tool_Issued', 'Tool Issued'), ('tool_Returned', 'Tool Returned'), ('tool_Damaged', 'Tool Damaged'), ('auto_logout', 'Auto Logout'), ('system_offline', 'System Offline'), ('system_online', 'System Online')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tooleventtracking',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tooleventtracking',
            name='tray_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
