# Generated by Django 5.2.7 on 2025-10-29 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0006_toolpurchase_quantity_toolpurchase_unit_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='batch_number',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='invoice_number',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='part_number',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='tool_name',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='inventory_id',
            field=models.CharField(editable=False, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='detection.toolcreation'),
        ),
    ]
