# Generated by Django 5.2.7 on 2025-10-29 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0007_remove_inventory_batch_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='In_stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
