# Generated by Django 5.2.7 on 2025-11-06 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0007_delete_toolevent_delete_toolstracking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='traytool',
            name='tool_id',
            field=models.CharField(default='unknown_tool', max_length=100),
        ),
    ]
