# Generated by Django 5.2.7 on 2025-11-07 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0008_delete_toolevent_traytool_tool_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ToolEvent',
        ),
        migrations.AlterField(
            model_name='tooleventtracking',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
