# Generated by Django 5.2.7 on 2025-10-29 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0008_inventory_in_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='In_stock',
            new_name='in_stock',
        ),
    ]
