# Generated by Django 5.2.7 on 2025-11-08 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0009_delete_toolevent_alter_tooleventtracking_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='tray',
            name='unit_code',
            field=models.CharField(default=1, editable=False, max_length=20),
            preserve_default=False,
        ),
    ]
