# Generated by Django 5.2.7 on 2025-10-30 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0010_servicestation_unit_tray'),
    ]

    operations = [
        migrations.AddField(
            model_name='tray',
            name='max_capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TrayTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_quantity', models.PositiveIntegerField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detection.inventory')),
                ('tray', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tray_tools', to='detection.tray')),
            ],
        ),
    ]
