# Generated by Django 5.2.7 on 2025-11-08 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0010_tray_unit_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tray',
            name='unit_code',
        ),
    ]
