# Generated by Django 5.2.7 on 2025-11-08 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0011_remove_tray_unit_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='tray',
            name='unit_id_code',
            field=models.CharField(default=1, editable=False, max_length=20),
            preserve_default=False,
        ),
    ]
