# Generated by Django 5.2.7 on 2025-11-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0012_tray_unit_id_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tray',
            name='unit_id_code',
        ),
        migrations.AddField(
            model_name='tray',
            name='unit_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
