# Generated by Django 5.2.7 on 2025-11-08 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0013_remove_tray_unit_id_code_tray_unit_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='station_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
