# Generated by Django 5.2.7 on 2025-11-03 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0015_toolstracking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='station',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='tray',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='unit',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='station_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='stations_display',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tray_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='trays_display',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='unit_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='units_display',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Supervisor', 'Supervisor'), ('Mechanic', 'Mechanic')], max_length=20, null=True),
        ),
    ]
