# Generated by Django 5.2.7 on 2025-11-08 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0016_profile_delete_userinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
