# Generated by Django 5.2.7 on 2025-11-03 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0016_remove_userprofile_station_remove_userprofile_tray_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='station_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='tray_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='unit_id',
        ),
    ]
