# Generated by Django 5.2.7 on 2025-11-08 10:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0017_profile_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='ProfileInforamtion',
        ),
    ]
