# Generated by Django 5.2.7 on 2025-11-08 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0019_profileinforamtion_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileinforamtion',
            name='role',
        ),
    ]
