# Generated by Django 5.2.7 on 2025-11-08 10:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0020_remove_profileinforamtion_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfileInforamtion',
            new_name='ProfileInformation',
        ),
    ]
