# Generated by Django 5.2.7 on 2025-11-08 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0021_rename_profileinforamtion_profileinformation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileinformation',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='profileinformation',
            name='profile_picture_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profileinformation',
            name='profile_picture_mime',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
