# Generated by Django 5.2.7 on 2025-11-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0022_remove_profileinformation_profile_picture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileinformation',
            name='profile_picture_data',
        ),
        migrations.RemoveField(
            model_name='profileinformation',
            name='profile_picture_mime',
        ),
        migrations.AddField(
            model_name='profileinformation',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
