# Generated by Django 5.2.7 on 2025-11-10 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0023_remove_profileinformation_profile_picture_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='stations_display',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='trays_display',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='units_display',
            field=models.TextField(blank=True, null=True),
        ),
    ]
