# Generated by Django 5.2.7 on 2025-11-10 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0024_alter_userprofile_stations_display_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tooleventtracking',
            name='unit_id',
            field=models.CharField(blank=True, null=True),
        ),
    ]
