# Generated by Django 5.2.7 on 2025-11-12 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0025_alter_tooleventtracking_unit_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aircraft_id', models.CharField(max_length=20, unique=True)),
                ('registration_no', models.CharField(max_length=20, unique=True)),
                ('model', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('airline_name', models.CharField(max_length=100)),
                ('flight_hours', models.PositiveIntegerField(default=0)),
                ('flight_cycles', models.PositiveIntegerField(default=0)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(editable=False, max_length=30, unique=True)),
                ('job_title', models.CharField(max_length=150)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('job_type', models.CharField(blank=True, max_length=100, null=True)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('PENDING_QA', 'Pending QA'), ('CLOSED', 'Closed'), ('ON_HOLD', 'On Hold')], default='CREATED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('bay_id', models.CharField(blank=True, max_length=30, null=True)),
                ('reported_issues', models.TextField(blank=True, null=True)),
                ('qa_approval_status', models.CharField(default='PENDING', max_length=20)),
                ('missing_tools_flag', models.BooleanField(default=False)),
                ('missing_tools_list', models.JSONField(blank=True, null=True)),
                ('tool_verification_completed', models.BooleanField(default=False)),
                ('documents', models.JSONField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='detection.aircraft')),
                ('assigned_technicians', models.ManyToManyField(blank=True, related_name='technician_jobs', to=settings.AUTH_USER_MODEL)),
                ('assigned_units', models.ManyToManyField(blank=True, related_name='jobcards', to='detection.unit')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_jobs', to=settings.AUTH_USER_MODEL)),
                ('qa_inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qa_jobs', to=settings.AUTH_USER_MODEL)),
                ('service_station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='detection.servicestation')),
            ],
        ),
        migrations.CreateModel(
            name='JobAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=100)),
                ('details', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='detection.jobcard')),
            ],
        ),
        migrations.CreateModel(
            name='JobToolUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_time', models.DateTimeField(blank=True, null=True)),
                ('returned_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ISSUED', 'Issued'), ('RETURNED', 'Returned'), ('MISSING', 'Missing')], default='ISSUED', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tool_issuers', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_usages', to='detection.jobcard')),
                ('returned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tool_returners', to=settings.AUTH_USER_MODEL)),
                ('tool', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tool_job_usages', to='detection.toolcreation')),
                ('tray', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tray_tool_usages', to='detection.tray')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_tool_usages', to='detection.unit')),
            ],
        ),
    ]
