# Generated by Django 5.2.7 on 2025-11-13 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0026_aircraft_jobcard_jobauditlog_jobtoolusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='tooleventtracking',
            name='job_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tooleventtracking',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tooleventtracking',
            name='verification_completed',
            field=models.BooleanField(default=False),
        ),
    ]
