# Generated by Django 5.2.7 on 2025-11-14 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0027_tooleventtracking_job_id_tooleventtracking_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicianStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_status', models.CharField(choices=[('AVAILABLE', 'Available'), ('BUSY', 'Busy'), ('ON_LEAVE', 'On Leave'), ('OFF_DUTY', 'Off Duty')], default='AVAILABLE', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('current_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='detection.jobcard')),
                ('technician', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UnitStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_status', models.CharField(choices=[('AVAILABLE', 'Available'), ('BUSY', 'Busy'), ('MAINTENANCE', 'Under Maintenance'), ('OFFLINE', 'Offline')], default='AVAILABLE', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('current_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='detection.jobcard')),
                ('unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='detection.unit')),
            ],
        ),
    ]
