# Generated by Django 5.2.7 on 2025-11-14 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0028_technicianstatus_unitstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unitstatus',
            name='current_job',
        ),
        migrations.RemoveField(
            model_name='unitstatus',
            name='unit',
        ),
        migrations.AddField(
            model_name='unit',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('BUSY', 'Busy'), ('MAINTENANCE', 'Under Maintenance'), ('OFFLINE', 'Offline')], default='AVAILABLE', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('BUSY', 'Busy'), ('ON_LEAVE', 'On Leave'), ('OFF_DUTY', 'Off Duty')], default='AVAILABLE', max_length=20),
        ),
        migrations.DeleteModel(
            name='TechnicianStatus',
        ),
        migrations.DeleteModel(
            name='UnitStatus',
        ),
    ]
