# Generated by Django 5.2.7 on 2025-11-17 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0029_remove_unitstatus_current_job_remove_unitstatus_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileinformation',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10),
        ),
    ]
