# Generated by Django 5.2.7 on 2025-11-18 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0030_profileinformation_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCardNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technician_id', models.CharField(max_length=100, null=True)),
                ('technician_name', models.CharField(max_length=255, null=True)),
                ('note_text', models.TextField()),
                ('working_component', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(max_length=50, null=True)),
                ('timestamp', models.DateTimeField()),
                ('device_id', models.CharField(max_length=255, null=True)),
                ('client_ip', models.CharField(max_length=255, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detection.jobcard')),
            ],
        ),
    ]
