# Generated by Django 5.2.7 on 2025-11-19 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0031_jobcardnotes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobcardnotes',
            old_name='note_text',
            new_name='description',
        ),
    ]
