# Generated by Django 5.2.7 on 2025-11-19 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0032_rename_note_text_jobcardnotes_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobcardnotes',
            name='client_ip',
        ),
        migrations.RemoveField(
            model_name='jobcardnotes',
            name='device_id',
        ),
    ]
