# Generated by Django 5.2.8 on 2025-11-25 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0033_remove_jobcardnotes_client_ip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicestation',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='servicestation',
            name='contact_person',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='servicestation',
            name='opening_hours',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('IN-USE', 'In-Use'), ('MAINTENANCE', 'Under Maintenance'), ('OFFLINE', 'Offline')], default='AVAILABLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('IN-USE', 'In-Use'), ('ON_LEAVE', 'On Leave'), ('OFF_DUTY', 'Off Duty')], default='AVAILABLE', max_length=20),
        ),
    ]
